fml – Fortran Matrix Lab
fml Program
51 statements
Source File
Uses
fml_lib
tm_module
bg_module
io_module
Main runtime - calls subroutines to set up model - sets up main timestep loop - calls biogeochemistry subroutines - calls subroutines to write model output
Calls
Contents
Variables
n nn t p count save_count start finish sum_val start2 finish2
Variables
Type Attributes Name Initial
integer :: n
various loop and counting indices
integer :: nn
various loop and counting indices
integer :: t
various loop and counting indices
integer :: p
various loop and counting indices
integer :: count
various loop and counting indices
integer :: save_count
various loop and counting indices
real :: start
variables to track elapsed
real :: finish
variables to track elapsed
real :: sum_val
variables to track elapsed
real :: start2
variables to track elapsed
real :: finish2
variables to track elapsed
Call graph
fml calls jatm, restore_atm_co2, timestep_fml, integrate_output, j, write_restart, write_po4_uptake, calc_pco2, water_column, po4_uptake, dop_remin, initialise_model, print_to_screen, calc_c_consts, calc_gasexchange, tm_vars_at_dt, load_namelist
restore_atm_co2 calls atm
timestep_fml calls jatm, amul, atm
integrate_output calls write_output_netcdf, atm_int, atm, write_timeseries_output
calc_pco2 calls c, c_consts, s_dt
water_column calls j, amul, amul_transpose
po4_uptake calls j, bg_po4_obs, bg_po4_uptake
dop_remin calls j
initialise_model calls jatm, print_to_screen, bg_po4_obs, tm_t, load_restart, load_data_saving, c, create_aconv, bunsen_coeffs, t_dt, c_consts, atm_int, find_water_columns, sc_coeffs, tm_s, bg_po4_uptake, s_dt, load_tm_grid_data, atm, load_tm_bgc_data, initialise_output, set_tm_timestep, calc_seasonal_scaling, sol_orr
print_to_screen calls atm
calc_c_consts calls t_dt, c_consts, s_dt
calc_gasexchange calls jatm, j, c, t_dt, sc_coeffs, s_dt, atm, sol_orr
tm_vars_at_dt calls tm_t, tm_s
write_output_netcdf calls nf90_close, nf90_strerror, nf90_inq_varid, nf90_open, v2f, nf90_put_var
load_tm_grid_data calls nf90_close, nf90_strerror, nf90_inq_varid, nf90_open, nf90_get_var
load_tm_bgc_data calls nf90_close, nf90_strerror, nf90_inq_varid, nf90_open, nf90_get_var
initialise_output calls initialise_timeseries_output, initialise_timeslice_output
write_timeseries_output calls atm_int
set_tm_timestep calls amub
initialise_timeslice_output calls nf90_close, nf90_strerror, nf90_create, nf90_def_dim, nf90_enddef, nf90_def_var
amub calls amub_nnz