calc_gasexchange – Fortran Matrix Lab
calc_gasexchange Subroutine
34 statements
Source File
public subroutine calc_gasexchange()
Calculate gas exchange between atmosphere and ocean - Orr et al., (2017) Geoscientific Model Development
Arguments
None
Calls
Called by
Contents
None
Call graph
calc_gasexchange calls jatm, j, sc_coeffs, t_dt, c, s_dt, sol_orr, atm
fml calls calc_gasexchange