initialise_output – Fortran Matrix Lab
initialise_output Subroutine
16 statements
Source File
public subroutine initialise_output()
Initialises timeslice and timeseries output files
creates output and restart directories if needed
Arguments
None
Calls
Called by
Contents
None
Call graph
initialise_output calls initialise_timeslice_output, initialise_timeseries_output
initialise_timeslice_output calls nf90_close, nf90_create, nf90_def_dim, nf90_strerror, nf90_enddef, nf90_def_var
initialise_model calls initialise_output
fml calls initialise_model