initialise_model – Fortran Matrix Lab
initialise_model Subroutine
165 statements
Source File
public subroutine initialise_model()
Initialises FML model
1) sets up array indices
2) allocates arrays
3) loads in matrix data
4) initialises parameters
5) initialises arrays
Arguments
None
Calls
Called by
Contents
None
Call graph
initialise_model calls jatm, bg_po4_obs, tm_t, load_restart, load_data_saving, c, create_aconv, bunsen_coeffs, t_dt, c_consts, print_to_screen, atm_int, find_water_columns, sc_coeffs, tm_s, bg_po4_uptake, s_dt, load_tm_grid_data, atm, load_tm_bgc_data, initialise_output, set_tm_timestep, calc_seasonal_scaling, sol_orr
print_to_screen calls atm
load_tm_grid_data calls nf90_close, nf90_strerror, nf90_inq_varid, nf90_open, nf90_get_var
load_tm_bgc_data calls nf90_close, nf90_strerror, nf90_inq_varid, nf90_open, nf90_get_var
initialise_output calls initialise_timeseries_output, initialise_timeslice_output
set_tm_timestep calls amub
initialise_timeslice_output calls nf90_close, nf90_strerror, nf90_create, nf90_def_dim, nf90_enddef, nf90_def_var
amub calls amub_nnz
fml calls initialise_model