initialise_timeslice_output – Fortran Matrix Lab
initialise_timeslice_output Subroutine
38 statements
Source File
public subroutine initialise_timeslice_output()
Initialises netCDF output
Arguments
None
Calls
Called by
Contents
None
Call graph
initialise_timeslice_output calls nf90_close, nf90_create, nf90_def_dim, nf90_strerror, nf90_enddef, nf90_def_var
initialise_output calls initialise_timeslice_output
initialise_model calls initialise_output
fml calls initialise_model