integrate_output – Fortran Matrix Lab
integrate_output Subroutine
31 statements
Source File
public subroutine integrate_output(loc_t, loc_save_count, loc_dt_count)
Average output and write to files if appropriate
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: loc_t
timestep
integer, intent(inout) :: loc_save_count
counter to keep track of number of save intervals
integer, intent(in) :: loc_dt_count
number of timesteps through averaging interval
Calls
Called by
Contents
None
Call graph
integrate_output calls write_timeseries_output, atm_int, atm, write_output_netcdf
write_timeseries_output calls atm_int
write_output_netcdf calls nf90_close, nf90_strerror, nf90_inq_varid, nf90_open, v2f, nf90_put_var
fml calls integrate_output