load_TM_data – Fortran Matrix Lab
load_TM_data Subroutine
17 statements
Source File
public subroutine load_TM_data()
Arguments
None
Calls
Contents
None
Call graph
load_tm_data calls load_po4_uptake, load_tm_bgc_data, load_martin_b_spatial, load_po4_restore, load_tm_grid_data
load_tm_bgc_data calls nf90_close, nf90_strerror, nf90_inq_varid, nf90_open, nf90_get_var
load_martin_b_spatial calls nf90_close, nf90_strerror, nf90_inq_varid, nf90_open, nf90_get_var
load_po4_restore calls nf90_close, nf90_strerror, nf90_inq_varid, nf90_open, nf90_get_var
load_tm_grid_data calls nf90_close, nf90_strerror, nf90_inq_varid, nf90_open, nf90_get_var