print_to_screen – Fortran Matrix Lab
print_to_screen Subroutine
7 statements
Source File
public subroutine print_to_screen(dum_t, dum_extra)
Print output to screen during runtime
Arguments
Type Intent Optional Attributes Name
integer :: dum_t
timestep
real :: dum_extra
not used
Calls
Called by
Contents
None
Call graph
print_to_screen calls atm
initialise_model calls print_to_screen
fml calls print_to_screen, initialise_model