set_TM_timestep – Fortran Matrix Lab
set_TM_timestep Subroutine
40 statements
Source File
public subroutine set_TM_timestep()
Applies timestep to transport matrices
Arguments
None
Calls
Called by
Contents
None
Call graph
set_tm_timestep calls amub
amub calls amub_nnz
initialise_model calls set_tm_timestep
fml calls initialise_model