write_output_netcdf – Fortran Matrix Lab
write_output_netcdf Subroutine
53 statements
Source File
public subroutine write_output_netcdf()
writes netCDF output
currently just for the last timestep!!
Arguments
None
Calls
Called by
Contents
None
Call graph
write_output_netcdf calls nf90_close, nf90_strerror, nf90_inq_varid, nf90_open, v2f, nf90_put_var
integrate_output calls write_output_netcdf
fml calls integrate_output